# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    application:
        name: HiOA Noark 5 Core (Production mode)
    profiles:
        active: prod
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/nikita_noark5_core_dev
        name: nikita_noark5_core_dev
        username: AAAAAAAAAAAAA
        password: AAAAAAAAAAAAA
        validation-query: SELECT 1;
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL82Dialect
        database: POSTGRESQL
        show_sql: true
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.search.default.directory_provider: filesystem
            hibernate.search.default.indexBase: target/lucene/indexes # This will probably be a /var/??? in production
            # Enable these to support elasticsearch, but wait until out of beta!
            #hibernate.search.default.indexmanager: elasticsearch
            #hibernate.search.default.elasticsearch.index_schema_management_strategy: MERGE # on applicatoin startup, use existing index
            #hibernate.search.default.elasticsearch.host: https://127.0.0.1:9876 # Only required if not using localhost

    mail:
        host: localhost
    messages:
        cache-seconds: 1
    thymeleaf:
        cache: false

server:
    port: 8443
    ssl:
        key-store: classpath:saml/nikitaKeystore.jks
        key-store-password: ************
        keyStoreType: PKCS12
        keyAlias: test-saml


# ===================================================================
# nikita-noark5-core specific properties
# ===================================================================

nikita-noark5-core:
    mail:
        from: nikita@example.com
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        spark:
            enabled: false
            host: localhost
            port: 9999
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: nikitaNoark5Core
        logs: # report metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512
    hibernate:
         dialect: org.hibernate.dialect.PostgreSQL82Dialect
         show_sql: false
         # hibernate.hbm2ddl.auto: create
         hbm2ddl.auto: update
    persistence:
         jpa.generateDdl: true
    server:
         name: nikita.hioa.no
         port: 8092
         address: 127.0.0.1